### ISSUE TITLE
Make portability compatible with XCode 10 command line tools..

### ISSUE THREAD

**Issue by oscarbg** [gfx-rs/portability#159]
Hi finally tried to build by myself and I get an error..

any clue?
```
cargo build --manifest-path libportability/Cargo.toml --features metal
   Compiling gfx-backend-metal v0.1.0 (https://github.com/gfx-rs/gfx#5f9f5237)
   Compiling objc_id v0.1.1
   Compiling cocoa v0.17.0
   Compiling cocoa v0.18.0
   Compiling objc-foundation v0.1.1
error: failed to run custom build command for `gfx-backend-metal v0.1.0 (https://github.com/gfx-rs/gfx#5f9f5237)`
process didn't exit successfully: `/Volumes/sierr6/Users/oscar/sep/portability/target/debug/build/gfx-backend-metal-f3b1debd56e7eb5a/build-script-build` (exit code: 101)
--- stdout
cargo:rerun-if-changed=/Users/oscar/.cargo/git/checkouts/gfx-e86e7f3ebdbc4218/5f9f523/src/backend/metal/shaders
cargo:rerun-if-changed=/Users/oscar/.cargo/git/checkouts/gfx-e86e7f3ebdbc4218/5f9f523/src/backend/metal/shaders/blit.metal
cargo:rerun-if-changed=/Users/oscar/.cargo/git/checkouts/gfx-e86e7f3ebdbc4218/5f9f523/src/backend/metal/shaders/macros.metal
cargo:rerun-if-changed=/Users/oscar/.cargo/git/checkouts/gfx-e86e7f3ebdbc4218/5f9f523/src/backend/metal/shaders/fill.metal
cargo:rerun-if-changed=/Users/oscar/.cargo/git/checkouts/gfx-e86e7f3ebdbc4218/5f9f523/src/backend/metal/shaders/clear.metal

--- stderr
metallib: Invalid bitcode file!
thread 'main' panicked at 'shader library build failed', /Users/oscar/.cargo/git/checkouts/gfx-e86e7f3ebdbc4218/5f9f523/src/backend/metal/build.rs:83:9
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: <std::panicking::begin_panic::PanicPayload<A> as core::panic::BoxMeUp>::get
             at libstd/panicking.rs:511
   5: std::panicking::begin_panic
             at /Users/travis/build/rust-lang/rust/src/libstd/panicking.rs:445
   6: build_script_build::main
             at ./build.rs:83
   7: std::rt::lang_start::{{closure}}
             at /Users/travis/build/rust-lang/rust/src/libstd/rt.rs:74
   8: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:310
   9: panic_unwind::dwarf::eh::read_encoded_pointer
             at libpanic_unwind/lib.rs:105
  10: std::sys_common::at_exit_imp::push
             at libstd/panicking.rs:289
             at libstd/panic.rs:392
             at libstd/rt.rs:58
  11: std::rt::lang_start
             at /Users/travis/build/rust-lang/rust/src/libstd/rt.rs:74
  12: build_script_build::main::{{closure}}

warning: build failed, waiting for other jobs to finish...
error: build failed

```

**Comment by oscarbg** [comment]
Hi,
maybe it's because I'm using Xcode 10 beta?
expected to work on Xcode 9 latest build?
thanks..

**Comment by kvark** [comment]
@oscarbg we currently require the command line tools from XCode 9, while we do actual debugging in XCode 10 (like GPU capturing). You can change the default toolset by going to XCode (menu) -> Preferences -> Locations (tab) -> Command Line Tools.

As for this issue, we can either close it, or rename to - make `portability` compatible with XCode 10 command line tools, which would be useful for sure, but nobody has looked at what needs to be done there yet.

**Comment by oscarbg** [comment]
@kvark 
thanks..
just renamed issue title, as Xcode 10 will become out of beta this month and more people might find same issue..

**Comment by kvark** [comment]
Fixed by https://github.com/gfx-rs/gfx/pull/2379
will close once we update to this gfx-rs version

**Comment by kvark** [comment]
Fixed by https://github.com/gfx-rs/portability/pull/162
